import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react'
import Banner from '../Components/banner.tsx'
import styles from '../styles/Home.module.css'

export default function Home() {

  const [buttonText , setButtonText] = useState("View Stores Nearby")

  const handleClick = () => {
    setButtonText("Loading...")
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Banner buttonText={buttonText} handleClick={handleClick}/>
      </main>
    </div>
  )
}
